"use strict";(self.webpackChunksonnet_docs=self.webpackChunksonnet_docs||[]).push([[2548],{4122:(e,n,t)=>{t.r(n),t.d(n,{assets:()=>i,contentTitle:()=>s,default:()=>d,frontMatter:()=>a,metadata:()=>c,toc:()=>h});var r=t(4848),o=t(8453);const a={slug:"error-handling-in-js",title:"Error Handling in JS",authors:{name:"Talha Mujahid",title:"Software Engineer",url:"https://github.com/htmujahid",image_url:"https://avatars.githubusercontent.com/u/58030954?v=4"},tags:["javascript"]},s="Error Handling in JS",c={permalink:"/blog/error-handling-in-js",editUrl:"https://github.com/sonnetjs/sonnetjs.github.io/tree/main/blog/javascript/16-error-handling-in-js.md",source:"@site/blog/javascript/16-error-handling-in-js.md",title:"Error Handling in JS",description:"JavaScript is a programming language that is widely used for creating dynamic and interactive web pages. Like other programming languages, it is important to handle errors that may occur during the execution of JavaScript code.",date:"2024-05-15T13:15:30.724Z",tags:[{label:"javascript",permalink:"/blog/tags/javascript"}],readingTime:5.07,hasTruncateMarker:!0,authors:[{name:"Talha Mujahid",title:"Software Engineer",url:"https://github.com/htmujahid",image_url:"https://avatars.githubusercontent.com/u/58030954?v=4",imageURL:"https://avatars.githubusercontent.com/u/58030954?v=4"}],frontMatter:{slug:"error-handling-in-js",title:"Error Handling in JS",authors:{name:"Talha Mujahid",title:"Software Engineer",url:"https://github.com/htmujahid",image_url:"https://avatars.githubusercontent.com/u/58030954?v=4",imageURL:"https://avatars.githubusercontent.com/u/58030954?v=4"},tags:["javascript"]},unlisted:!1,prevItem:{title:"Scheduling in JS",permalink:"/blog/scheduling-in-js"},nextItem:{title:"Advanced Datatypes in JS",permalink:"/blog/advanced-datatypes-in-js"}},i={authorsImageUrls:[void 0]},h=[];function l(e){const n={code:"code",h1:"h1",li:"li",ol:"ol",p:"p",pre:"pre",strong:"strong",ul:"ul",...(0,o.R)(),...e.components};return(0,r.jsxs)(r.Fragment,{children:[(0,r.jsx)(n.p,{children:"JavaScript is a programming language that is widely used for creating dynamic and interactive web pages. Like other programming languages, it is important to handle errors that may occur during the execution of JavaScript code."}),"\n",(0,r.jsx)(n.h1,{id:"types-of-errors-in-js",children:"Types of Errors in JS"}),"\n",(0,r.jsx)(n.p,{children:"There are three types of errors that can occur in JavaScript code:"}),"\n",(0,r.jsxs)(n.ol,{children:["\n",(0,r.jsxs)(n.li,{children:[(0,r.jsx)(n.strong,{children:"Syntax Errors"}),": These are errors that occur when there is a mistake in the syntax of the code. For example, missing semicolons or brackets can cause syntax errors."]}),"\n",(0,r.jsxs)(n.li,{children:[(0,r.jsx)(n.strong,{children:"Runtime Errors"}),": These are errors that occur during the execution of the code. For example, trying to access an undefined variable can cause a runtime error."]}),"\n",(0,r.jsxs)(n.li,{children:[(0,r.jsx)(n.strong,{children:"Logical Errors"}),": These are errors that occur when the code does not do what it is supposed to do. For example, a function that returns the wrong value."]}),"\n"]}),"\n",(0,r.jsx)(n.h1,{id:"error-handling-techniques-in-js",children:"Error Handling Techniques in JS"}),"\n",(0,r.jsx)(n.p,{children:"There are several techniques that can be used to handle errors in JavaScript code:"}),"\n",(0,r.jsx)(n.h1,{id:"try-catch-statement",children:"Try-Catch Statement"}),"\n",(0,r.jsx)(n.p,{children:"In JavaScript, the try-catch statement is used to handle exceptions or errors that may occur in a block of code. The try block contains the code that may cause an exception, and the catch block handles the exception if it is thrown."}),"\n",(0,r.jsx)(n.p,{children:"Here\u2019s the basic syntax of the try-catch statement in JavaScript:"}),"\n",(0,r.jsx)(n.pre,{children:(0,r.jsx)(n.code,{className:"language-js",children:"try {  \n  // code that may cause an exception  \n} catch (error) {  \n  // code to handle the exception  \n}\n"})}),"\n",(0,r.jsxs)(n.p,{children:["The ",(0,r.jsx)(n.code,{children:"**try**"})," block contains the code that may cause an exception. If an exception is thrown, JavaScript will jump out of the ",(0,r.jsx)(n.code,{children:"**try**"})," block and into the ",(0,r.jsx)(n.code,{children:"**catch**"})," block. The ",(0,r.jsx)(n.code,{children:"**catch**"})," block takes an error object as a parameter, which contains information about the exception that was thrown."]}),"\n",(0,r.jsx)(n.p,{children:"Here\u2019s an example that demonstrates the use of the try-catch statement in JavaScript:"}),"\n",(0,r.jsx)(n.pre,{children:(0,r.jsx)(n.code,{className:"language-js",children:"javascriptCopy code  \nfunction divide(a, b) {  \n  try {  \n    if (b === 0) {  \n      throw new Error('Cannot divide by zero');  \n    }  \n    return a / b;  \n  } catch (error) {  \n    console.log(error.message);  \n    return null;  \n  }  \n}  \nconsole.log(divide(10, 5)); // Output: 2  \nconsole.log(divide(10, 0)); // Output: Cannot divide by zero, null\n"})}),"\n",(0,r.jsxs)(n.p,{children:["When an exception is thrown and caught using a ",(0,r.jsx)(n.code,{children:"**catch**"})," block, the ",(0,r.jsx)(n.code,{children:"**catch**"})," block receives an ",(0,r.jsx)(n.code,{children:"**error**"})," object that contains information about the exception that was thrown. The ",(0,r.jsx)(n.code,{children:"**error**"})," object has several properties that you can use to get more information about the exception. Some of the most commonly used properties are:"]}),"\n",(0,r.jsxs)(n.ul,{children:["\n",(0,r.jsxs)(n.li,{children:[(0,r.jsx)(n.code,{children:"**message**"}),": A string that contains a description of the exception."]}),"\n",(0,r.jsxs)(n.li,{children:[(0,r.jsx)(n.code,{children:"**name**"}),": A string that contains the name of the exception. This is usually the name of the constructor function that was used to create the exception."]}),"\n",(0,r.jsxs)(n.li,{children:[(0,r.jsx)(n.code,{children:"**stack**"}),": A string that contains a stack trace of the call stack at the time the exception was thrown. This can be useful for debugging purposes."]}),"\n"]}),"\n",(0,r.jsxs)(n.p,{children:["Here is an example that demonstrates how to use the ",(0,r.jsx)(n.code,{children:"**error**"})," object to handle an exception:"]}),"\n",(0,r.jsx)(n.pre,{children:(0,r.jsx)(n.code,{className:"language-js",children:"try {  \n  // Some code that might throw an exception  \n} catch (error) {  \n  console.error('An error occurred:', error.message);  \n  console.error('Error name:', error.name);  \n  console.error('Stack trace:', error.stack);  \n}\n"})}),"\n",(0,r.jsx)(n.h1,{id:"throw-statement",children:"Throw Statement"}),"\n",(0,r.jsxs)(n.p,{children:["In JavaScript, the ",(0,r.jsx)(n.code,{children:"**throw**"})," statement is used to throw an exception. When an exception is thrown, the JavaScript interpreter immediately stops executing the current function and looks for the nearest exception handling code to catch and handle the exception."]}),"\n",(0,r.jsxs)(n.p,{children:["The basic syntax for the ",(0,r.jsx)(n.code,{children:"**throw**"})," statement is as follows:"]}),"\n",(0,r.jsx)(n.pre,{children:(0,r.jsx)(n.code,{className:"language-js",children:"throw expression;\n"})}),"\n",(0,r.jsxs)(n.p,{children:["The ",(0,r.jsx)(n.code,{children:"**expression**"})," can be any value or object that represents the exception that you want to throw. For example, you can throw a string, a number, an object, or an error."]}),"\n",(0,r.jsxs)(n.p,{children:["Here is an example that demonstrates how to use the ",(0,r.jsx)(n.code,{children:"**throw**"})," statement to throw a custom error message:"]}),"\n",(0,r.jsx)(n.pre,{children:(0,r.jsx)(n.code,{className:"language-js",children:"function divide(a, b) {  \n  if (b === 0) {  \n    throw 'Cannot divide by zero';  \n  }  \n  return a / b;  \n}  \nconsole.log(divide(10, 0)); // Throws \"Cannot divide by zero\" exception\n"})}),"\n",(0,r.jsx)(n.h1,{id:"finally-block",children:"Finally Block"}),"\n",(0,r.jsxs)(n.p,{children:["The ",(0,r.jsx)(n.code,{children:"**finally**"})," block is a part of a ",(0,r.jsx)(n.code,{children:"**try...catch**"})," statement in JavaScript. It is used to execute code that should always run, regardless of whether an exception was thrown or not. The ",(0,r.jsx)(n.code,{children:"**finally**"})," block is optional, but if it is present, it is always executed, even if there is no ",(0,r.jsx)(n.code,{children:"**catch**"})," block."]}),"\n",(0,r.jsx)(n.p,{children:"Here\u2019s an example:"}),"\n",(0,r.jsx)(n.pre,{children:(0,r.jsx)(n.code,{className:"language-js",children:"try {  \n  // Code that may throw an exception  \n  // ...  \n} catch (error) {  \n  // Code to handle the exception  \n  // ...  \n} finally {  \n  // Code that should always run  \n  // ...  \n}\n"})}),"\n",(0,r.jsxs)(n.p,{children:["In this example, the ",(0,r.jsx)(n.code,{children:"**try**"})," block contains code that may throw an exception. If an exception is thrown, the ",(0,r.jsx)(n.code,{children:"**catch**"})," block is executed to handle it. If there is no exception, the ",(0,r.jsx)(n.code,{children:"**catch**"})," block is skipped."]}),"\n",(0,r.jsxs)(n.p,{children:["Regardless of whether an exception was thrown or not, the code in the ",(0,r.jsx)(n.code,{children:"**finally**"})," block is always executed. This can be useful for performing cleanup tasks, such as closing files or releasing resources."]}),"\n",(0,r.jsxs)(n.p,{children:["Here\u2019s an example of how you could use the ",(0,r.jsx)(n.code,{children:"**finally**"})," block:"]}),"\n",(0,r.jsx)(n.pre,{children:(0,r.jsx)(n.code,{className:"language-js",children:"function divide(a, b) {  \n  try {  \n    return a / b;  \n  } catch (error) {  \n    console.error('An error occurred:', error);  \n  } finally {  \n    console.log('Division operation completed');  \n  }  \n}  \nconsole.log(divide(10, 2));  // Output: 5  \nconsole.log(divide(10, 0));  // Output: Infinity\n"})}),"\n",(0,r.jsx)(n.h1,{id:"custom-error-class",children:"Custom Error Class"}),"\n",(0,r.jsxs)(n.p,{children:["In JavaScript, you can create custom error classes by extending the built-in ",(0,r.jsx)(n.code,{children:"**Error**"})," class. This can be useful when you want to create specific types of errors for your application that have their own unique properties and behaviors. Here's an example of how you can create a custom error class:"]}),"\n",(0,r.jsx)(n.pre,{children:(0,r.jsx)(n.code,{className:"language-js",children:"class MyError extends Error {  \n  constructor(message, code) {  \n    super(message);  \n    this.code = code;  \n    this.name = 'MyError';  \n  }  \n}\n"})}),"\n",(0,r.jsx)(n.p,{children:"Here\u2019s an example of how you can use this custom error class:"}),"\n",(0,r.jsx)(n.pre,{children:(0,r.jsx)(n.code,{className:"language-js",children:'function myFunction() {  \n  throw new MyError(\'An error occurred\', 500);  \n}  \ntry {  \n  myFunction();  \n} catch (error) {  \n  console.error(error.name);    // Output: "MyError"  \n  console.error(error.message); // Output: "An error occurred"  \n  console.error(error.code);    // Output: 500  \n}\n'})}),"\n",(0,r.jsx)(n.p,{children:"In conclusion, error handling is an important part of writing JavaScript code. By using techniques such as try-catch statements, throw statements, and finally blocks, you can effectively handle errors that may occur during the execution of your code."})]})}function d(e={}){const{wrapper:n}={...(0,o.R)(),...e.components};return n?(0,r.jsx)(n,{...e,children:(0,r.jsx)(l,{...e})}):l(e)}},8453:(e,n,t)=>{t.d(n,{R:()=>s,x:()=>c});var r=t(6540);const o={},a=r.createContext(o);function s(e){const n=r.useContext(a);return r.useMemo((function(){return"function"==typeof e?e(n):{...n,...e}}),[n,e])}function c(e){let n;return n=e.disableParentContext?"function"==typeof e.components?e.components(o):e.components||o:s(e.components),r.createElement(a.Provider,{value:n},e.children)}}}]);